doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '15'

        profiling_collect_backtrace: '%kernel.debug%'
        use_savepoints: true
        mapping_types:
            enum: string
            geometry: geometry
        types:
            listing_status_enum: App\Shared\ORM\ListingStatus\ListingStatusType
            geometry: App\Shared\ORM\Spatial\DoctrineType\GeometryType
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            User:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Core/User/Entity'
                prefix: 'App\Core\User\Entity'
                alias: User
            Listing:
                type: xml
                is_bundle: false
                dir: '%kernel.project_dir%/src/ORM/Mappings/Listing'
                prefix: 'App\Core\Listing'
                alias: Listing
            Renting:
                type: xml
                is_bundle: false
                dir: '%kernel.project_dir%/src/ORM/Mappings/Renting'
                prefix: 'App\Core\Renting'
                alias: Renting
        dql:
            numeric_functions:
                ST_Distance: App\Shared\ORM\Spatial\Functions\StDistance
                ST_GeomFromText: App\Shared\ORM\Spatial\Functions\StGeomFromText
when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
