api_login_check:
    path: /api/v1/login_check

user_controller:
    resource:
        path: ../src/Core/User/Controller
        namespace: App\Core\User\Controller
    type:
        attribute

host_controller:
    resource:
        path: ../src/Core/Host/Controller
        namespace: App\Core\Host\Controller
    type:
        attribute

renting_controller:
    resource:
        path: ../src/Core/Renting/Controller
        namespace: App\Core\Renting\Controller
    type:
        attribute

search_controller:
    resource:
        path: ../src/Core/Search/Controller
        namespace: App\Core\Search\Controller
    type:
        attribute

listing_controller:
    resource:
        path: ../src/Core/Listing/Controller
        namespace: App\Core\Listing\Controller
    type:
        attribute