user_controller:
    resource:
        path: ../src/Core/User/Controller
        namespace: App\Core\User\Controller
    type:
        attribute

search_controller:
    resource:
        path: ../src/Core/Search/Controller
        namespace: App\Core\Search\Controller
    type:
        attribute

listing_controller:
    resource:
        path: ../src/Core/Listing/Controller
        namespace: App\Core\Listing\Controller
    type:
        attribute